name: PlaywrightTests
 - task: Npm@1
  inputs:
    command: 'install'

trigger:
  - main
  - master

jobs:
- job: test
  timeoutInMinutes: 60
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - checkout: self

  - task: Node@16
- task: CmdLine@2
  inputs:
    script: 'npm install --global'
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm ci
    displayName: "Install dependencies"

  - script: |
      npx playwright install --with-deps
    displayName: "Install Playwright Browsers"

  - script: |
      npx playwright test
    displayName: "Run Playwright tests"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(System.DefaultWorkingDirectory)/playwright-report"
      artifact: "playwright-report"
      publishLocation: "pipeline"
    condition: always()
