name: PlaywrightTests

variables:
  CI: true

trigger:
  - main

jobs:
  - job: test
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install Project Dependencies"

      - script: |
          npx playwright install
        displayName: "Install Playwright Browsers"

      - script: |
          npx playwright test
        displayName: "Run Playwright Tests"
