steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
- task: Npm@1
  inputs:
    command: 'install'
- task: CmdLine@2
  inputs:
    script: 'npm install -D playwright-core'